version: "3.9"

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodlepass
      - MARIADB_DATABASE=bitnami_moodle
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: always
    depends_on:
      - mariadb
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpass
      - MOODLE_SITE_NAME="My Moodle"
      - MOODLE_EMAIL=user@example.com
    ports:
      - "8081:8080"
    volumes:
      - moodle_data:/bitnami/moodle

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    environment:
      - MEILI_MASTER_KEY=key123
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  mariadb_data:
  moodle_data:
  meili_data:
