services:
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: key123
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
